### ISSUE TITLE
Suspected bug, crash on Windows

### ISSUE THREAD

**Issue by yayxs** [wevm/vocs#190] opened 2024-07-19 01:34 UTC
## error log

 [running] vocs@v1.0.0-alpha.55

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
09:29:08 [vite] Pre-transform error: Failed to load url /@
fsD:\gh-code\vocs-test\node_modules\.pnpm\vocs@1.0.0-alpha.55_@types+node@20.14.11_@types+react@18.3.3_react-dom@18.3.1_react@18.3.1__r_vxkgqtqghr4r632nugm7h56sd4\node_modules\vocs\_lib\app/index.client.js (resolved id: /@ fsD:\gh-code\vocs-test\node_modules\.pnpm\vocs@1.0.0-alpha.55_@types+node@20.14.11_@types+react@18.3.3_react-dom@18.3.1_react@18.3.1__r_vxkgqtqghr4r632nugm7h56sd4\node_modules\vocs\_lib\app/index.client.js). Does the file exist?
09:29:09 [vite] Pre-transform error: Failed to load url D:gh-codeocs-test
ode_modules.pnpmocs@1.0.0-alpha.55_@types+node@20.14.11_@types+react@18.3.3_react-dom@18.3.1_react@18.3.1__r_vxkgqtqghr4r632nugm7h56sd4
ode_modulesocs_libite.vocs    heme.css (resolved id: D:gh-codeocs-test
ode_modules.pnpmocs@1.0.0-alpha.55_@types+node@20.14.11_@types+react@18.3.3_react-dom@18.3.1_react@18.3.1__r_vxkgqtqghr4r632nugm7h56sd4
ode_modulesocs_libite.vocs    heme.css) in virtual:styles. Does the file exist?
09:29:13 [vite] Pre-transform error: Failed to load url /@ fsD:\gh-code\vocs-test\node_modules\.pnpm\vocs@1.0.0-alpha.55_@types+node@20.14.11_@types+react@18.3.3_react-dom@18.3.1_react@18.3.1__r_vxkgqtqghr4r632nugm7h56sd4\node_modules\vocs\_lib\app/index.client.js (resolved id: /@ fsD:\gh-code\vocs-test\node_modules\.pnpm\vocs@1.0.0-alpha.55_@types+node@20.14.11_@types+react@18.3.3_react-dom@18.3.1_react@18.3.1__r_vxkgqtqghr4r632nugm7h56sd4\node_modules\vocs\_lib\app/index.client.js). Does the file exist?

## package information
```json
{
  "name": "vocs-test",
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vocs dev",
    "build": "vocs build",
    "preview": "vocs preview"
  },
  "dependencies": {
    "@types/react": "latest",
    "react": "latest",
    "react-dom": "latest",
    "typescript": "latest",
    "vocs": "latest"
  }
}
```

## Other environments

- windows
- node v20.11.1
- pnpm 9.0.6

**Comment by jxom** [comment] 2024-10-04 10:02
dupe of https://github.com/wevm/vocs/issues/52

**Closed by jxom** 2024-10-04 10:02 UTC
