### ISSUE TITLE
BUG Site Broken Hard Refresh

### ISSUE THREAD

**Issue by codingwithmanny** [wevm/vocs#109] opened 2024-02-19 20:42 UTC
# Context

The site literally breaks if going a to subsection and trying to refresh.
<img width="1624" alt="Screenshot 2024-02-19 at 11 40 11 PM" src="https://github.com/wevm/vocs/assets/318082/1852dd17-3dc7-4b34-bf22-45d764c07db9">

# Steps To Reproduce

1 - Go to [https://vocs.dev/docs](https://vocs.dev/docs)
2 - Click on `Blog` or any sidebar link and wait for the page to load
3 - Refresh the page and see that the page is broken

# Potential Solution

It looks like the paths to the assets are set to relative vs absolute.

<img width="1624" alt="Screenshot 2024-02-19 at 11 42 45 PM" src="https://github.com/wevm/vocs/assets/318082/87622fbc-56ad-4ed3-b2bb-e7ba23468de0">

**Comment by jxom** [comment] 2024-02-19 20:52
I can't reproduce this.

**Comment by jxom** [comment] 2024-02-19 21:07
Closing as I am assuming this could have been an issue between deployments.

**Comment by jxom** [comment] 2024-02-19 21:08
can reproduce now, will fix

**Comment by jxom** [comment] 2024-02-19 21:16
Fixed: fcec0937fb34978f539f4f7b5d34105378d94447

**Closed by jxom** 2024-02-19 21:16 UTC
