### ISSUE TITLE
🐛 Build error: Rollup failed to resolve import

### ISSUE THREAD

**Issue by SivertGullbergHansen** [wevm/vocs#127] opened 2024-03-03 01:47 UTC
Command: `yarn build`
Not sure what to make of this, as I have little to no knowledge with Rollup and Vite 🧑‍🚀
(Project was made using the command `yarn create vocs`)

The error in question:
```sh
PS C:\Users\Sivert\Desktop\tournament\docs> yarn build
yarn run v1.22.21
warning package.json: No license field
$ vocs build

  [building] vocs@v1.0.0-alpha.40

✖ bundles failed to build: [vite]: Rollup failed to resolve import "C:UsersSivertDesktop        ournamentdocs
ode_modules
ocs_lib
ite.vocs        heme.css" from "virtual:styles".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

In the file `virtual-styles.ts` we are trying to import this css file... 
![image](https://github.com/wevm/vocs/assets/6785315/06fe80b1-3111-4318-bc17-07687e8c7944)

Something about importing an empty css file?
![image](https://github.com/wevm/vocs/assets/6785315/357a0093-5991-4c27-8b07-6070ea934d7d)

**Comment by chengpeiquan** [comment] 2024-03-03 14:10
Looks like it's related to #52 , I tried fixing it at PR #128 .

**Comment by SivertGullbergHansen** [comment] 2024-03-04 09:11
☝🏼 Indeed, and I also noticed I cannot start dev mode now. It happened after building, and I assume somehow the build stopped before it finished, which destroyed my project 😛

**Comment by jxom** [comment] 2024-10-04 10:06
Dupe of #52.

**Closed by jxom** 2024-10-04 10:06 UTC
