### ISSUE TITLE
"Error when evaluating SSR module" when running vocs dev / build

### ISSUE THREAD

**Issue by Sam-Scolari** [wevm/vocs#171] opened 2024-05-23 05:19 UTC
After creating a fresh project through `npm init vocs` and installing the packages, I get the following error

```bash
[vite] Error when evaluating SSR module C:\Users\samsc\Documents\GitHub\emotes\node_modules\vocs\_lib\app\index.server.js: failed to import "/@fs/C:/Users/samsc/Documents/GitHub/emotes/node_modules/vocs/_lib/app/routes.js"
|- Error: Cannot find module 'C:UserssamscDocumentsGitHubemotes
ode_modules
ocs_lib
ite.vocs        heme.css' imported from 'virtual:styles'
    at nodeImport (file:///C:/Users/samsc/Documents/GitHub/emotes/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:55089:25)
    at ssrImport (file:///C:/Users/samsc/Documents/GitHub/emotes/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:54998:30)
    at eval (virtual:styles:3:50)
    at instantiateModule (file:///C:/Users/samsc/Documents/GitHub/emotes/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:55058:15)

node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Cannot find module 'C:UserssamscDocumentsGitHubemotes
ode_modules
ocs_lib
ite.vocs        heme.css' imported from 'virtual:styles'
    at nodeImport (file:///C:/Users/samsc/Documents/GitHub/emotes/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:55089:25)
    at ssrImport (file:///C:/Users/samsc/Documents/GitHub/emotes/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:54998:30)
    at eval (virtual:styles:3:50)
    at instantiateModule (file:///C:/Users/samsc/Documents/GitHub/emotes/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:55058:15) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v21.3.0
error: script "dev" exited with code 1
```

I have back tested to version `1.0.0-alpha.40` and in both **Node** and **Bun** runtimes on Windows with the same issue

**Comment by nordowl** [comment] 2024-07-07 01:06
Did you find a fix for this?

**Comment by jxom** [comment] 2024-10-04 10:03
dupe of #52

**Closed by jxom** 2024-10-04 10:03 UTC
